analyzer:
  strong-mode: true
  exclude:
    - web/giant_widgets.dart
    - others/**
    - dist/**
    - build/**
    - CMakeFiles/**

linter:
  rules:
    - await_only_futures
    - unawaited_futures
